document.write('if (teste lógico){<br>')
document.write('comando}<br>')
document.write('else if (teste logico caso o 1 seja negativo){<br>')
document.write('comando}')
document.write('else{comando caso as duas primeiras tenha dado negativo}')